### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by corny** [Crowd9/Benchmark#18]
The `sb.sh` does not upload the results:

```
[...]
Running traceroute...
Running ping benchmark...
Running UnixBench benchmark...
Uploading results...
Response: error
Completed! Your benchmark has been queued & will be delivered in a jiffy.
```

It's a very bad idea to not check the exit code of `curl`. The results are also deleted after not being uploaded.

I started the benchmark on an minimal installation of Ubuntu 14.04.4.

**Comment by ponny** [comment]
Underling elastic search was broken, sorry.  Fixed now.

**Comment by corny** [comment]
I suggest:
- Server: Accept the upload and process it asynchronously. A broken elastic search should not affect receiving uploads.
- Script: Only delete results if upload was successful.
