### ISSUE TITLE
Response Error

### ISSUE THREAD

**Issue by maxisme** [Crowd9/Benchmark#19]
When running a bench I get a response error when uploading the results:

<img src="https://pbs.twimg.com/media/CjFle5tWkAAh-6j.png:large"/>

**Comment by unixfox** [comment]
https://twitter.com/serverbear/status/765034545703813121

**Comment by maxisme** [comment]
@unixfox That is very sad. Do you know or recommend any alternatives?

**Comment by unixfox** [comment]
Sure I use this alternative : https://serverscope.io
